config/routes.rb
Rails.application.routes.draw do
  resources :reports, only: [:index] do
    get 'land_payments', on: :collection
    get 'apple_payments', on: :collection

  end

  resources :refinancied_sales, only: [:index, :new, :create]
  resources :payments
  resources :credit_notes
  resources :payment_methods
  resources :provider_roles
  post 'disable_provider_role', to: 'provider_roles#disable', as: 'disable_provider_role'
  resources :projects
  

  resources :urbanizations, except: [:destroy, :show]
  post 'disable_urbanization', to: 'urbanizations#disable', as: 'disable_urbanization'
  resources :sectors, except: [:destroy, :show]
  post 'disable_sector', to: 'sectors#disable', as: 'disable_sector'
  resources :condominia, except: [:destroy, :show]
  post 'disable_condominium', to: 'condominia#disable', as: 'disable_condominium'
  resources :apples, except: [:destroy, :show] do 
    resources :lands, except: [:show, :destroy]
  end
  post 'disable_apple', to: 'apples#disable', as: 'disable_apple'
  post 'disable_land', to: 'lands#disable', as: 'disable_land'
  resources :clients, except: [:destroy, :show] do
    get 'lands_by_client', on: :member
    resources :contacts,  except: [:destroy, :show] do 
      get "modal_disable", on: :member
      post "disable", on: :member
    end
  end
  post 'disable_client', to: 'clients#disable', as: 'disable_client'
  resources :providers, except: [:destroy, :show]
  post 'disable_provider', to: 'providers#disable', as: 'disable_provider'
  resources :materials, except: [:destroy, :show]
  post 'disable_material', to: 'materials#disable', as: 'disable_material'
  resources :sales, except: [:show] do
    post 'create_bought', on: :collection
    get 'payment_summary', on: :member
    patch 'set_payment_plan', on: :member
    resources :adjusts, only: [:new, :create]
  end
  post 'disable_sale', to: 'sales#disable', as: 'disable_sale'
  resources :project_types
  post 'disable_project_type', to: 'project_types#disable', as: 'disable_project_type'
  # detalle de las ventas de un lote (venta de tierra y projectos)
  get 'detail_sales', to: 'lands#detail_sales', as: 'land_detail_sales'
  get '/sectors/filter_for_urbanization/:urbanization_id', to: 'sectors#filter_for_urbanization'
  get '/apples/filter_for_sector/:sector_id', to: 'apples#filter_for_sector'

  # Fees routes
  get 'detalle_pagos/:id', to: 'fees#details', as: 'detalle_pagos'
  resources :fees, only: [:show,:create, :new, :update] 
  # End fees routes 

  post '/sale_project', to: "sales#sale_project", as: 'sale_project'

  post 'disable_fee_payment', to: 'fee_payments#disable', as: 'disable_fee_payment'


  get 'fees/modal_apply_adjust/:sale_id', to: "fees#modal_apply_adjust", as: 'modal_apply_adjust'
  post 'fees/apply_adjust', to: "fees#apply_adjust", as: 'apply_adjust'

  resources :payments_types
  resources :currencies
  resource :payments_currencies
  
  root 'clients#index'
  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  namespace :authentication, path: '', as: '' do
    resources :users, only: [:index,:new, :create]
    resources :sessions, only: [:create]
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
  end
end

app/models/apple.rb
# == Schema Information
#
# Table name: apples
#
#  id                  :bigint           not null, primary key
#  code                :string(100)      not null
#  hectares            :decimal(15, 2)   default(0.0), not null
#  value               :decimal(15, 2)   default(0.0), not null
#  space_not_available :decimal(15, 2)   default(0.0)
#  condominium_id      :bigint
#  sector_id           :bigint
#  active              :boolean          default(TRUE), not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
class Apple < ApplicationRecord
  belongs_to :condominium
  belongs_to :sector
  has_many :lands
  has_one :urbanization, through: :sector
  has_one_attached :blueprint

  validates :code, presence: true,
    uniqueness: {  scope: :sector_id, case_sensitive: false, message: "Ya existe una manzana con esta denominación en este sector" }

  scope :actives, -> { where(active: true) }

  def has_corner
    self.lands.where(is_corner: true).count > 0
  end

  def count_corners
    self.lands.where(is_corner: true).count
  end

  def get_all_pay
    all_pay = 0 
    self.lands.each do |land|
      all_pay += land.get_all_pay
    end
    all_pay
  end

  def get_all_owes
    all_owes = 0 
    self.lands.each do |land|
      all_owes += land.get_all_owes
    end
    all_owes
  end

  def total_price
    total_price = 0
    self.lands.each do |land|
      total_price += land.total_price
    end
    total_price
  end

  def owes_this_month
    pay_this_month = 0
    self.lands.each do |land|
      pay_this_month += land.owes_this_month
    end
    pay_this_month
  end

  def paid_this_month
    paid = 0
    self.lands.each do |land|
      paid += land.paid_this_month
    end
    paid
  end

  def get_all_increments
    increments = 0 
    self.lands.each do |land|
      increments += land.get_all_increments
    end
    increments
  end

  def get_value
    apple_value = 0
    self.lands.each do |land|
      apple_value += land.get_value
    end
    apple_value
  end
end

app/controllers/apples_controller.rb
class ApplesController < ApplicationController
  before_action :set_apple, only: %i[ show edit update destroy ]

  def index
    @apples = Apple.actives.includes(:sector)
  end

  def show
  end

  def filter_for_sector
    @apples = Apple.where( sector_id: params[:sector_id] ).where( active: true ).order(:code)
  end

  def new
    @title_modal = "Agregar manzana"
    @sectors = Sector.where(active: true)
    @condominia = Condominium.where(active: true)
    @apple = Apple.new
  end

  def edit
    @title_modal = "Editar manzana"
    @sectors = Sector.where(active: :true)
    @condominia = Condominium.where(active: true)
  end

  def create
    @apple = Apple.new(apple_params)

    respond_to do |format|
      if @apple.save
        format.json { render json: { status: 'success', msg: 'Manzana registrada' }, status: :created }
      else
        format.json { render json: @apple.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @apple.update(apple_params)
        format.json { render json: { status: 'success', msg: 'Datos actualizados' }, status: :ok, location: @apple }
      else
        format.json { render json: @apple.errors, status: :unprocessable_entity }
      end
    end
  end

  def disable
    @apple = Apple.find(params[:apple_id])
    if @apple.update!(active: false)
      render json: { status: 'success', msg: 'Manzana eliminada' }, status: :ok
    else
      render json: { status: 'error', msg: 'Ocurrio un error al realizar la operación' }, status: :unprocessable_entity
    end

    rescue => e
      @response = e.message.split(':')
      render json: { @response[0] => @response[1] }, status: 402
  end

  private
    def set_apple
      @apple = Apple.find(params[:id])
    end

    def apple_params
      params.require(:apple).permit(:code, :hectares, :value, :space_not_available, :condominium_id, :sector_id, :active, :blueprint)
    end
end

app/views/apples/_form.html.erb
<%= form_with(model: @apple, id: 'form-apple' ,class: 'needs-validation g-brd-around g-brd-gray-light-v4 g-pa-30 g-mb-10') do |form| %>
  <div class="form-group row">
    <%= form.label :code, 'Denominacion (*):' ,class: 'col-8 col-sm-4' %>
    <%= form.text_field :code, class: 'form-control rounded-0 col-12 col-sm-6', required: true %>
    <div class="invalid-feedback apple_code"></div>
  </div>

  <div class="form-group row">
    <%= form.label :hectares, 'N° hectareas:' ,class: 'col-8 col-sm-4' %>
    <%= form.number_field :hectares, class: 'form-control rounded-0 col-12 col-sm-6', step:'0.001' %>
    <div class="invalid-feedback apple_hectares"></div>
  </div>

  <div class="form-group row">
    <%= form.label :space_not_available, 'Superficie no utilizable (m²):' ,class: 'col-8 col-sm-4' %>
    <%= form.number_field :space_not_available, class: 'form-control rounded-0 col-12 col-sm-6', step:'0.0001'%>
    <div class="invalid-feedback apple_space_not_available"></div>
  </div>

  <div class="form-group row">
    <div class="col-8 col-sm col-lg-9">
      <%= form.select(:sector_id, @sectors.collect {|s| ["#{s.urbanization.name} - #{s.name}", s.id]}, { include_blank: true},
                      class: 'form-control select-2-apple', required: true) %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :value, 'Valor ($):' ,class: 'col-8 col-sm-4' %>
    <%= form.number_field :value, class: 'form-control rounded-0 col-12 col-sm-6', step:'0.001' %>
    <div class="invalid-feedback apple_value"></div>
  </div>

  <div class="form-group row">
    <div class="col-8 col-sm col-lg-9">
      <%= form.select(:condominium_id, @condominia.collect {|c| ["#{c.name}", c.id]}, { include_blank: true},
                      class: 'form-control select-2-condominium', required: true) %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar', class: 'btn u-btn-teal mr-2'  %>
    <button type="button" class="btn u-btn-darkred" data-dismiss="modal">Cerrar</button>
  </div>
<% end %>

app/views/apples/edit.js.erb
$("#modal").html("<%= j (render partial: 'shared/modal', locals:{ size: 'lg' } ) %>")

$('.select-2-apple').select2({ width: '100%',theme: "bootstrap4", placeholder: "Seleccione un sector (*)" })
$('.select-2-condominium').select2({ width: '100%',theme: "bootstrap4", placeholder: "Seleccione un condominio (*)" })

$("#modal").modal('show')

$("#form-apple").on("ajax:success", function(event) {
    apples_table.ajax.reload(null,false)
    let msg = JSON.parse(event.detail[2].response)
    noty_alert(msg.status, msg.msg)
    $("#modal").modal('hide')
  }).on("ajax:error", function(event) {
	let msg = JSON.parse(event.detail[2].response)
	console.info(msg)
	$.each( msg, function( key, value ) {
		$(`#form-apple #apple_${key}`).addClass('is-invalid')
		$(`#form-apple .apple_${key}`).text( value ).show('slow')
	})
})

app/views/apples/index.html.erb
<h1>Manzanas</h1>

<%= link_to 'Agregar manzana', new_apple_path, {:remote => true, 'data-toggle' =>  "modal",
      'data-target' => '#modal-apple', 'class' => 'btn u-btn-teal justify-content-end mb-2'} %>

<%= link_to 'Condominios', condominia_path, class: 'btn u-btn-blue justify-content-end mb-2 ml-4', title: 'Ver condominios registrados' %>

<table id="apples-table" class="table hover dt-responsive w-100">
  <thead>
    <tr>
      <th>Denominacion</th>
      <th>Hectareas</th>
      <th>Merma</th>
      <th>Ubicacion</th>
      <th>Valor</th>
      <th>Sector</th>
      <th>Condominio</th>
      <th>Acciones</th>
  </thead>
  <tbody>
  </tbody>
</table> 

<!-- Modal alta de apple -->
<div class="modal fade" id="modal-apple" role="dialog"
     aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
</div>
<!-- End modal -->


<!-- Modal para eliminar apple -->
<div class="modal fade" id="modal-disable-apple" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">¿ Esta seguro de quitar la manzana ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="alert alert-danger" role="alert">
          Tenga en cuenta que todos los registros asociados tambien seran dados de baja.
          <span data-toggle="collapse" href="#multiCollapseExample1" 
                role="button" aria-expanded="false" aria-controls="multiCollapseExample1"  
                class="badge badge-info">Leer mas...</span>
            <div class="collapse multi-collapse" id="multiCollapseExample1">
              Registros afectados:
              <ul>
                <li>Lotes de la manzana</li>
              </ul>
            </div>
        </div>
        <%= form_with(url: disable_apple_path, id: 'form-disable-apple') do |form| %>
          <%= form.hidden_field :apple_id %>
          <%= form.submit 'Eliminar', class: 'btn u-btn-red g-mr-10' %>
          <button type="button" data-dismiss="modal" class="btn u-btn-teal g-mr-10"> Cerrar </button>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Fin modal eliminar apple -->

app/views/apples/new.js.erb
$("#modal").html("<%= j (render partial: 'shared/modal', locals:{ size: 'lg' } ) %>")

$('.select-2-apple').select2({ width: '100%',theme: "bootstrap4", placeholder: "Seleccione un sector (*)" })
$('.select-2-condominium').select2({ width: '100%',theme: "bootstrap4", placeholder: "Seleccione un condominio (*)" })

$("#modal").modal('show')

$("#form-apple").on("ajax:success", function(event) {
    apples_table.ajax.reload(null,false)
    let msj = JSON.parse(event.detail[2].response)
    noty_alert(msj.status, msj.msg)
    $("#modal").modal('hide')
  }).on("ajax:error", function(event) {
	let msj = JSON.parse( event.detail[2].response )
	$.each( msj, function( key, value ) {
		$(`#form-apple #apple_${key}`).addClass('is-invalid')
		$(`#form-apple .apple_${key}`).text( value ).show('slow')
	})
})

app/views/apples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @apple.code %>
</p>

<p>
  <strong>Hectares:</strong>
  <%= @apple.hectares %>
</p>

<p>
  <strong>Value:</strong>
  <%= @apple.value %>
</p>

<p>
  <strong>Space not available:</strong>
  <%= @apple.space_not_available %>
</p>

<p>
  <strong>Condominium:</strong>
  <%= @apple.condominium %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @apple.sector %>
</p>

<p>
  <strong>Active:</strong>
  <%= @apple.active %>
</p>

<%= link_to 'Edit', edit_apple_path(@apple) %> |
<%= link_to 'Back', apples_path %>