config/routes.rb
Rails.application.routes.draw do
  resources :reports, only: [:index] do
    get 'land_payments', on: :collection
    get 'apple_payments', on: :collection

  end

  resources :refinancied_sales, only: [:index, :new, :create]
  resources :payments
  resources :credit_notes
  resources :payment_methods
  resources :provider_roles
  post 'disable_provider_role', to: 'provider_roles#disable', as: 'disable_provider_role'
  resources :projects
  

  resources :urbanizations, except: [:destroy, :show]
  post 'disable_urbanization', to: 'urbanizations#disable', as: 'disable_urbanization'
  resources :sectors, except: [:destroy, :show]
  post 'disable_sector', to: 'sectors#disable', as: 'disable_sector'
  resources :condominia, except: [:destroy, :show]
  post 'disable_condominium', to: 'condominia#disable', as: 'disable_condominium'
  resources :apples, except: [:destroy, :show] do 
    resources :lands, except: [:show, :destroy]
  end
  post 'disable_apple', to: 'apples#disable', as: 'disable_apple'
  post 'disable_land', to: 'lands#disable', as: 'disable_land'
  resources :clients, except: [:destroy, :show] do
    get 'lands_by_client', on: :member
    resources :contacts,  except: [:destroy, :show] do 
      get "modal_disable", on: :member
      post "disable", on: :member
    end
  end
  post 'disable_client', to: 'clients#disable', as: 'disable_client'
  resources :providers, except: [:destroy, :show]
  post 'disable_provider', to: 'providers#disable', as: 'disable_provider'
  resources :materials, except: [:destroy, :show]
  post 'disable_material', to: 'materials#disable', as: 'disable_material'
  resources :sales, except: [:show] do
    post 'create_bought', on: :collection
    get 'payment_summary', on: :member
    patch 'set_payment_plan', on: :member
    resources :adjusts, only: [:new, :create]
  end
  post 'disable_sale', to: 'sales#disable', as: 'disable_sale'
  resources :project_types
  post 'disable_project_type', to: 'project_types#disable', as: 'disable_project_type'
  # detalle de las ventas de un lote (venta de tierra y projectos)
  get 'detail_sales', to: 'lands#detail_sales', as: 'land_detail_sales'
  get '/sectors/filter_for_urbanization/:urbanization_id', to: 'sectors#filter_for_urbanization'
  get '/apples/filter_for_sector/:sector_id', to: 'apples#filter_for_sector'

  # Fees routes
  get 'detalle_pagos/:id', to: 'fees#details', as: 'detalle_pagos'
  resources :fees, only: [:show,:create, :new, :update] 
  # End fees routes 

  post '/sale_project', to: "sales#sale_project", as: 'sale_project'

  post 'disable_fee_payment', to: 'fee_payments#disable', as: 'disable_fee_payment'


  get 'fees/modal_apply_adjust/:sale_id', to: "fees#modal_apply_adjust", as: 'modal_apply_adjust'
  post 'fees/apply_adjust', to: "fees#apply_adjust", as: 'apply_adjust'

  resources :payments_types
  resources :currencies
  resource :payments_currencies
  
  root 'clients#index'
  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  namespace :authentication, path: '', as: '' do
    resources :users, only: [:index,:new, :create]
    resources :sessions, only: [:create]
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
  end
end

app/controllers/condominia_controller.rb
class CondominiaController < ApplicationController
  before_action :set_condominium, only: %i[ show edit update destroy ]

  def index
    @condominia = Condominium.actives
  end

  def new
    @condominium = Condominium.new
  end

  def edit
  end

  def create
    @condominium = Condominium.new(condominium_params)

    respond_to do |format|
      if @condominium.save
        format.json { render json: { status: 'success', msg: 'Condominio registrado' }, status: :created }
      else
        format.json { render json: @condominium.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @condominium.update(condominium_params)
        format.json { render json: { status: 'success', msg: 'Datos actualizados' }, status: :ok }
      else
        format.json { render json: @condominium.errors, status: :unprocessable_entity }
      end
    end
  end

  def disable
    @condominium = Condominium.find(params[:condominium_id])
    if @condominium.update(active:false)
      render json: { status: 'success', msg: 'Condominio eliminado' }, status: :ok
    else
      render json: { status: 'error', msg: 'Ocurrio un error al realizar la operación' }, status: :unprocessable_entity
    end

    rescue => e
      @response = e.message.split(':')
      render json: { @response[0] => @response[1] }, status: 402
  end

  private
    def set_condominium
      @condominium = Condominium.find(params[:id])
    end

    def condominium_params
      params.require(:condominium).permit(:name, :description, :active)
    end
end

app/views/condominia/_form.html.erb
<%= form_with(model: @condominium, id: 'form-condominium', class: 'needs-validation g-brd-around g-brd-gray-light-v4 g-pa-30 g-mb-30') do |form| %>

  <div class="form-group row">
    <div class="col-3">
      <%= form.label :name, 'Nombre (*):'%>
    </div>
    <div class="col-6">
      <%= form.text_field :name, class: 'form-control form-control-sm rounded-0', required: true %>
      <div class="invalid-feedback sector_name"></div>
    </div>
  </div>

  <div class="form-group">
    <%= form.text_area :description, 
        placeholder: "Descripción",
        class: "form-control form-control-md u-textarea-expandable g-brd-gray-light-v7 g-brd-gray-light-v3--focus rounded-0 g-resize-none g-overflow-hidden" %>
  </div>

  <div class="mt-4">
    <%= form.submit 'Guardar', class: 'btn u-btn-teal mr-2'  %>
    <button type="button" class="btn u-btn-darkred" data-dismiss="modal">Cerrar</button>
  </div>
<% end %>

app/views/condominia/edit.js.erb
$("#modal").html("<%= j (render partial: 'shared/modal', locals:{ size: 'lg' } ) %>")
$("#modal").modal('show')

$("#form-condominium").on("ajax:success", function(event) {
    condominia_table.ajax.reload(null,false)
    let msg = JSON.parse(event.detail[2].response)
    noty_alert(msg.status, msg.msg)
    $("#modal").modal('hide')
  }).on("ajax:error", function(event) {
		let msg = JSON.parse(event.detail[2].response)
		console.info(msg)
		$.each( msg, function( key, value ) {
			$(`#form-condominium #condominium_${key}`).addClass('is-invalid')
			$(`#form-condominium .condominium_${key}`).text( value ).show('slow')
		})
})

app/views/condominia/index.html.erb
<h1><i class="hs-admin-stamp"></i> Condominios</h1>
<%= link_to '<i class="hs-admin-back-left"></i>Volver a manzanas'.html_safe, 
    apples_path, 
    class: 'btn u-btn-outline-pink u-btn-hover-v1-2 mb-2' %>
<%= link_to '<i class="fa fa-plus"></i> Registrar condominio'.html_safe, 
    new_condominium_path, 
    { :remote => true, 'data-toggle' =>  "modal", 
     'data-target' => '#modal-condominium', 
     'class' => 'btn u-btn-teal justify-content-end mb-2 ml-4'} %>
<table id="condominia-table" class="table hover dt-responsive w-100">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>


<!-- Modal alta de condominium -->
<div class="modal fade" id="modal-condominium" role="dialog"
     aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
</div>
<!-- End modal -->


<!-- Modal para eliminar condominium -->
<div class="modal fade" id="modal-disable-condominium" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">¿ Esta seguro de dar de baja al proveedor ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(url: disable_condominium_path, id: 'form-disable-condominium') do |form| %>
          <%= form.hidden_field :condominium_id %>
          <%= form.submit 'Eliminar', class: 'btn u-btn-red g-mr-10' %>
          <button type="button" data-dismiss="modal" class="btn u-btn-teal g-mr-10"> Cerrar </button>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Fin modal eliminar condominium -->

app/views/condominia/new.js.erb
$("#modal").html("<%= j (render partial: 'shared/modal', locals:{ size: 'lg' } ) %>")

$("#modal").modal('show')

$("#form-condominium").on("ajax:success", function(event) {
    condominia_table.ajax.reload(null,false)
    let msj = JSON.parse(event.detail[2].response)
    noty_alert(msj.status, msj.msg)
    $("#modal").modal('hide')
  }).on("ajax:error", function(event) {
	let msj = JSON.parse( event.detail[2].response )
	$.each( msj, function( key, value ) {
		$(`#form-condominium #condominium_${key}`).addClass('is-invalid')
		$(`#form-condominium .condominium_${key}`).text( value ).show('slow')
	})
})

app/views/condominia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @condominium.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @condominium.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @condominium.active %>
</p>

<%= link_to 'Edit', edit_condominium_path(@condominium) %> |
<%= link_to 'Back', condominia_path %>