config/routes.rb
Rails.application.routes.draw do
  resources :reports, only: [:index] do
    get 'land_payments', on: :collection
    get 'apple_payments', on: :collection

  end

  resources :refinancied_sales, only: [:index, :new, :create]
  resources :payments
  resources :credit_notes
  resources :payment_methods
  resources :provider_roles
  post 'disable_provider_role', to: 'provider_roles#disable', as: 'disable_provider_role'
  resources :projects
  

  resources :urbanizations, except: [:destroy, :show]
  post 'disable_urbanization', to: 'urbanizations#disable', as: 'disable_urbanization'
  resources :sectors, except: [:destroy, :show]
  post 'disable_sector', to: 'sectors#disable', as: 'disable_sector'
  resources :condominia, except: [:destroy, :show]
  post 'disable_condominium', to: 'condominia#disable', as: 'disable_condominium'
  resources :apples, except: [:destroy, :show] do 
    resources :lands, except: [:show, :destroy]
  end
  post 'disable_apple', to: 'apples#disable', as: 'disable_apple'
  post 'disable_land', to: 'lands#disable', as: 'disable_land'
  resources :clients, except: [:destroy, :show] do
    get 'lands_by_client', on: :member
    resources :contacts,  except: [:destroy, :show] do 
      get "modal_disable", on: :member
      post "disable", on: :member
    end
  end
  post 'disable_client', to: 'clients#disable', as: 'disable_client'
  resources :providers, except: [:destroy, :show]
  post 'disable_provider', to: 'providers#disable', as: 'disable_provider'
  resources :materials, except: [:destroy, :show]
  post 'disable_material', to: 'materials#disable', as: 'disable_material'
  resources :sales, except: [:show] do
    post 'create_bought', on: :collection
    get 'payment_summary', on: :member
    patch 'set_payment_plan', on: :member
    resources :adjusts, only: [:new, :create]
  end
  post 'disable_sale', to: 'sales#disable', as: 'disable_sale'
  resources :project_types
  post 'disable_project_type', to: 'project_types#disable', as: 'disable_project_type'
  # detalle de las ventas de un lote (venta de tierra y projectos)
  get 'detail_sales', to: 'lands#detail_sales', as: 'land_detail_sales'
  get '/sectors/filter_for_urbanization/:urbanization_id', to: 'sectors#filter_for_urbanization'
  get '/apples/filter_for_sector/:sector_id', to: 'apples#filter_for_sector'

  # Fees routes
  get 'detalle_pagos/:id', to: 'fees#details', as: 'detalle_pagos'
  resources :fees, only: [:show,:create, :new, :update] 
  # End fees routes 

  post '/sale_project', to: "sales#sale_project", as: 'sale_project'

  post 'disable_fee_payment', to: 'fee_payments#disable', as: 'disable_fee_payment'


  get 'fees/modal_apply_adjust/:sale_id', to: "fees#modal_apply_adjust", as: 'modal_apply_adjust'
  post 'fees/apply_adjust', to: "fees#apply_adjust", as: 'apply_adjust'

  resources :payments_types
  resources :currencies
  resource :payments_currencies
  
  root 'clients#index'
  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  namespace :authentication, path: '', as: '' do
    resources :users, only: [:index,:new, :create]
    resources :sessions, only: [:create]
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                 :bigint           not null, primary key
#  number             :integer          not null
#  name               :string(255)
#  active             :boolean          default(TRUE)
#  price              :decimal(15, 2)   default(0.0), not null
#  subtotal           :decimal(15, 2)   default(0.0), not null
#  final_price        :decimal(15, 2)   default(0.0), not null
#  status             :integer          default("pendiente")
#  description        :text(65535)
#  land_price         :decimal(15, 2)   default(0.0), not null
#  land_corner_price  :decimal(15, 2)   default(0.0), not null
#  project_type_id    :bigint
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  date               :date             not null
#  first_pay_required :boolean          default(TRUE)
#  first_pay_price    :decimal(15, 2)
#
class Project < ApplicationRecord
  attribute :finalized, :boolean

	has_many :project_providers, dependent: :destroy
  has_many :project_materials, dependent: :destroy
  has_many :land_projects, dependent: :destroy
  has_many :apple_projects, dependent: :destroy
  belongs_to :project_type

  has_many :providers, through: :project_providers
  has_many :materials, through: :project_materials
  has_many :lands, through: :land_projects
  has_many :payment_plans, dependent: :destroy

  accepts_nested_attributes_for :project_providers, :project_materials,:apple_projects, :land_projects, :payment_plans

  validates :land_price, :land_corner_price, 
    presence: true
    # numericality: { greater_than: 0 }
  validates :number, presence: true, numericality: { only_integer: true }
  validates :date,:price, :subtotal, :final_price, presence: true
  
  after_create :check_is_finalized

  scope :actives, -> { where(active: true) }
  
  enum status: [:pendiente, :proceso, :terminado]

  def sector_name
    if !self.lands.empty?
      self.lands.first.sector.name
    end
  end

  def project_status
    lands = self.land_projects.count
    pending = self.land_projects.where(status: :pending).count
    process = self.land_projects.where(status: :process).count
    payed = self.land_projects.where(status: :payed).count
    status_label = ''

    if lands == pending
      status_label = 'Pendiente'
    end

    if process > 0
      status_label = 'En proceso'
    end

    if lands == payed
      status_label = 'Completado'
    end

    status_label
  end

  def get_all_owes
    owes = 0
    sale_products = SaleProduct.where( product: self )
    sale_products.each do |sale_product|
      owes += sale_product.sale.get_all_owes
    end
    owes
  end

  def get_all_pay
    paid = 0
    sale_products = SaleProduct.where( product: self )
    sale_products.each do |sale_product|
      paid += sale_product.sale.saldo_pagado
    end
    paid
  end
  
  private
  def check_is_finalized
    # if this project is created with finalized in true means that
    # it's a old project and was paid. Then I must create the land_projects paid with one quote
    if self.finalized
      self.land_projects.update_all( status: :payed )
      sale_products = SaleProduct.where(product: self)
      sale_products.each do |sale_product|
        # get fee to pay
        sale = sale_product.sale
        pay = sale.fees.first.value
        sale.payments.create(
          date: self.date,
          payments_currency_id: 1,
          payment: pay,
          taken_in: 1,
          total: pay,
          comment: "Pago completo del proyecto."
        )
        sale.fees.first.update(pay_status: :pagado, payed: true, payment: pay, pay_date: self.date)
        sale.update(status: :payed)
      end
      self.update(status: :terminado)
    end
  end
end

app/models/project_type.rb
# == Schema Information
#
# Table name: project_types
#
#  id          :bigint           not null, primary key
#  active      :boolean          default(TRUE)
#  description :string(255)      default("")
#  name        :string(255)      not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class ProjectType < ApplicationRecord
	validates :name, presence: true

	scope :actives, -> { where(active: true) }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  def index
    @projects = Project.all
  end

  def show
    @title_modal = "Información del projecto"
    @status_color = 'lightblue'
  end

  def new
    @project = Project.new
    @project_type = ProjectType.actives.order(:name)
    @materials = Material.actives.order(:name)
    @providers = Provider.actives.order(:name)
    @sectors = Sector.where(active: true)
    @urbanizations = Urbanization.actives.order(:name)
    @provider_roles = ProviderRole.where(active: true).order(:name)
    @payment_methods = PaymentMethod.where(active: true).order(:name)
  end

  def edit
  end

  def create
    ActiveRecord::Base.transaction do 
      project = Project.new(project_params)
      project.price = 0
      if project.save
        render json: {status: 'success', msg: 'Proyecto registrado con exito'}, status: :ok
      end
    end
    rescue => e
      @response = e.message.split(':')
      puts @response
      render json: {status: 'error', msg: 'No se pudo registrar el proyecto'}, status: 402
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:number, :name, :active, :price, :total, :status,:final_price,:subtotal,:description,:project_type_id, 
        :land_corner_price, :land_price, :date, :finalized, :first_pay_required, :first_pay_price,
        project_providers_attributes: [:id, :provider_id,:provider_role_id,:payment_method_id,:price,:iva,:value_iva,:price_calculate,:porcent,:type_total, :porcent_from],
        project_materials_attributes: [:id, :material_id,:type_units,:units,:price],
        payment_plans_attributes: [ :id, :number, :category, :price, :date, :option ],
        apple_projects_attributes: [:id, :apple_id],
        land_projects_attributes: [:id, :land_id, :finalized,:status,:price,:price_quotas, :price_quotas_corner ])
    end
end

app/views/projects/_show.html.erb
<div class="modal-dialog modal-xl" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title"><%= @title_modal%></h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <h3 class="g-font-weight-300 g-font-size-20 g-color-black g-mb-15"><%= @project.name %></h3>
      <span class="u-tags-v1 text-center g-width-130 g-brd-around g-brd-<%= @status_color %>-v3 g-bg-<%= @status_color %>-v3 g-color-white g-rounded-50 g-py-4 g-px-15">  <%= @project.project_status %>
      </span>
      <hr class="d-flex g-brd-gray-light-v7 g-mx-20 g-mx-30--sm my-10">
      <em class="g-font-style-normal g-font-weight-500 g-font-size-16 g-color-gray-dark-v6">Estado financiacion</em>
      <div class="row mb-4 mt-4">
        <%= render(partial: 'lands/card_pay',  
                  locals: { color: 'lightred-v2', paid: @project.final_price, detail: 'Debe' })%>
        <%= render(partial: 'lands/card_pay', 
                  locals: { color: 'teal-v2', paid: @project.get_all_pay, detail: 'Haber' })%>
        <%= render(partial: 'lands/card_pay', 
                  locals: { color: 'purple', paid: @project.get_all_owes, detail: 'Saldo' })%>
      </div>
      <div class="card-block d-flex justify-content-between g-px-20 g-px-30--sm g-py-15 g-py-20--sm">
        <div>
          <h4 class="g-line-height-1_2 g-font-weight-300 g-font-size-28 g-color-black">
            <%= @project.land_projects.where(status: :pending).count %>
          </h4>
          <em class="g-font-style-normal g-font-weight-300 g-font-size-16 g-color-gray-dark-v6">Pendientes</em>
        </div>
        <div>
          <h4 class="g-line-height-1_2 g-font-weight-300 g-font-size-28 g-color-black">
            <%= @project.land_projects.where(status: :process).count %>
            </h4>
          <em class="g-font-style-normal g-font-weight-300 g-font-size-16 g-color-gray-dark-v6">En proceso</em>
        </div>
        <div>
          <h4 class="g-line-height-1_2 g-font-weight-300 g-font-size-28 g-color-black">
            <%= @project.land_projects.where(status: :payed).count %>
            </h4>
          <em class="g-font-style-normal g-font-weight-300 g-font-size-16 g-color-gray-dark-v6">Pagados</em>
        </div>
      </div>
      <div class="card-block g-px-20 g-px-30--sm g-py-15 g-py-20--sm">
        <div class="g-mb-25">
          <h5 class="g-font-size-default g-color-gray-dark-v6 g-mb-5">Intervinientes</h5>
          <table class="table table-sm table-striped text-center">
            <thead>
              <th>Interviniente</th>
              <th>Función</th>
              <th>Precio</th>
              <th>IVA</th>
              <th>Valor IVA</th>
              <th>TOTAL</th>
              <th>% representa TOTAL </th>
            </thead>
            <tbody>
              <% @project.project_providers.intervinientes.actives.each do |provider| %>
                <tr>
                  <td><%= provider.provider.name %></td>
                  <td><%= provider.provider_role.name %></td>
                  <td><%= format_currency(provider.price) %></td>
                  <td><%= provider.iva %></td>
                  <td><%= "#{provider.value_iva}%" %></td>
                  <td><%= "$#{format_currency(provider.price_calculate)}" %></td>
                  <td><%= "#{provider.porcent}%" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="card-block g-px-20 g-px-30--sm g-py-15 g-py-20--sm">
        <div class="g-mb-25">
          <h5 class="g-font-size-default g-color-gray-dark-v6 g-mb-5">Otros intervinientes</h5>
          <table class="table table-sm table-striped text-center">
            <thead>
              <th>Interviniente</th>
              <th>Función</th>
              <th>%</th>
              <th>IVA</th>
              <th>Valor IVA</th>
              <th>TOTAL</th>
              <th>% representa TOTAL </th>
            </thead>
            <tbody>
              <% @project.project_providers.otros_intervinientes.actives.each do |provider| %>
                <tr>
                  <td><%= provider.provider.name %></td>
                  <td><%= provider.provider_role.name %></td>
                  <td><%= provider.price %>% de <%= provider.porcent_from%></td>
                  <td><%= provider.iva %></td>
                  <td><%= "#{provider.value_iva}%" %></td>
                  <td><%= "$#{format_currency(provider.price_calculate)}" %></td>
                  <td><%= "#{provider.porcent}%" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="card-block g-px-20 g-px-30--sm g-py-15 g-py-20--sm">
        <div class="g-mb-25">
          <h5 class="g-font-size-default g-color-gray-dark-v6 g-mb-5">Materiales</h5>
          <table class="table table-sm table-striped text-center">
            <thead>
              <th>Material</th>
              <th>Tipo de unidad</th>
              <th>Unidades</th>
              <th>Precio por unidad</th>
              <th>Total</th>
            </thead>
            <tbody>
              <% @project.project_materials.actives.each do |material| %>
                <tr>
                  <td><%= material.material.name %></td>
                  <td><%= material.type_units %></td>
                  <td><%= material.units %></td>
                  <td><%= "$#{format_currency(material.price)}" %></td>
                  <td><%= "$#{format_currency(material.price * material.units)}" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="mb-2 ml-2">
      <button type="button" class="btn u-btn-teal" data-dismiss="modal" aria-label="Close"> Cerrar </button>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Proyectos</h1>
<div class="row justify-content-between">
  <div class="col-4">
    <%= link_to 'Agregar proyecto', new_project_path, class:'btn u-btn-primary justify-content-end mb-2' %>
  </div>
  <div class="col-4">
    <%= link_to 'Tipos de proyectos', project_types_path, class:'btn u-btn-cyan justify-content-end mb-2' %>
  </div>
</div>

<table id="projects_table" class="table hover dt-responsive w-100">
  <thead>
    <tr>
      <th>#</th>
      <th>Categoría</th>
      <th>Nombre</th>
      <th>Sector</th>
      <th>Manzana</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.number %></td>
        <td><%= project.project_type.name %></td>
        <td><%= project.name %></td>
        <td>
          <%= project.lands&.first&.apple&.sector&.name %>
        </td>
        <td>
          <%= project.lands&.first&.apple&.code %>
        </td>
        <td>
          <%= link_to 'Detalle', project_path(project), class: 'btn u-btn-teal btn-sm', remote: true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- Modal alta de apple -->
<div class="modal fade" id="modal-project" role="dialog"
     aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
</div>
<!-- End modal -->

app/views/projects/new.html.erb
<h1>Nuevo proyecto</h1>

<%= render 'form', project: @project %>

app/views/projects/show.js.erb
$("#modal").html("<%= j (render 'show' ) %>")

$("#modal").modal('show')